### ISSUE TITLE
Method has non-conform DID Core Datetime

### ISSUE THREAD

**Issue by BernhardFuchs** [decentralized-identity/uni-resolver-driver-did-ccp#5]
When running the [did-test-suite](https://github.com/w3c/did-test-suite) the method has 4 failing tests, all related to `DID Core Datetime`:
```
  ● 7.1.x DID Resolution - Universal Resolver - Decentralized Identity Foundation and Contributors › did:ccp:3CzQLF3qfFVQ1CjGVzVRZaFXrjAd (expected outcome: defaultOutcomes) › DID Document Metadata › created › 7.1.3 DID Document Metadata - The value of the property MUST be a string formatted as an XML Datetime normalized to UTC 00:00:00 and without sub-second decimal precision.

    expect(received).toBeDidCoreDatetime()

    Expected value to be of a valid DID Core Datetime:
      "a valid DID Core Datetime"
    Received:
      "2019-10-23T09:14:17.961Z"

      185 |     if (didDocumentMetadata.hasOwnProperty('created')) {
      186 |       it('7.1.3 DID Document Metadata - The value of the property MUST be a string formatted as an XML Datetime normalized to UTC 00:00:00 and without sub-second decimal precision.', async () => {
    > 187 |         expect(didDocumentMetadata['created']).toBeDidCoreDatetime();
          |                                                ^
      188 |       });
      189 |     }
      190 |   });

      at Object.<anonymous> (suites/did-resolution/did-resolution.js:187:48)

  ● 7.1.x DID Resolution - Universal Resolver - Decentralized Identity Foundation and Contributors › did:ccp:3CzQLF3qfFVQ1CjGVzVRZaFXrjAd (expected outcome: defaultOutcomes) › DID Document Metadata › updated › 7.1.3 DID Document Metadata - The value of the property MUST follow the same formatting rules as the created property.

    expect(received).toBeDidCoreDatetime()

    Expected value to be of a valid DID Core Datetime:
      "a valid DID Core Datetime"
    Received:
      "2019-10-23T09:14:17.961Z"

      192 |     if (didDocumentMetadata.hasOwnProperty('updated')) {
      193 |       it('7.1.3 DID Document Metadata - The value of the property MUST follow the same formatting rules as the created property.', async () => {
    > 194 |         expect(didDocumentMetadata['updated']).toBeDidCoreDatetime();
          |                                                ^
      195 |       });
      196 |       if (didDocumentMetadata.hasOwnProperty('created')) {
      197 |         it('7.1.3 DID Document Metadata - updated is later or equal than created.', async () => {

      at Object.<anonymous> (suites/did-resolution/did-resolution.js:194:48)

  ● 7.1.x DID Resolution - Universal Resolver - Decentralized Identity Foundation and Contributors › did:ccp:ceNobbK6Me9F5zwyE3MKY88QZLw (expected outcome: defaultOutcomes) › DID Document Metadata › created › 7.1.3 DID Document Metadata - The value of the property MUST be a string formatted as an XML Datetime normalized to UTC 00:00:00 and without sub-second decimal precision.

    expect(received).toBeDidCoreDatetime()

    Expected value to be of a valid DID Core Datetime:
      "a valid DID Core Datetime"
    Received:
      "2019-10-21T11:12:13.065Z"

      185 |     if (didDocumentMetadata.hasOwnProperty('created')) {
      186 |       it('7.1.3 DID Document Metadata - The value of the property MUST be a string formatted as an XML Datetime normalized to UTC 00:00:00 and without sub-second decimal precision.', async () => {
    > 187 |         expect(didDocumentMetadata['created']).toBeDidCoreDatetime();
          |                                                ^
      188 |       });
      189 |     }
      190 |   });

      at Object.<anonymous> (suites/did-resolution/did-resolution.js:187:48)

  ● 7.1.x DID Resolution - Universal Resolver - Decentralized Identity Foundation and Contributors › did:ccp:ceNobbK6Me9F5zwyE3MKY88QZLw (expected outcome: defaultOutcomes) › DID Document Metadata › updated › 7.1.3 DID Document Metadata - The value of the property MUST follow the same formatting rules as the created property.

    expect(received).toBeDidCoreDatetime()

    Expected value to be of a valid DID Core Datetime:
      "a valid DID Core Datetime"
    Received:
      "2019-10-21T11:17:49.379Z"

      192 |     if (didDocumentMetadata.hasOwnProperty('updated')) {
      193 |       it('7.1.3 DID Document Metadata - The value of the property MUST follow the same formatting rules as the created property.', async () => {
    > 194 |         expect(didDocumentMetadata['updated']).toBeDidCoreDatetime();
          |                                                ^
      195 |       });
      196 |       if (didDocumentMetadata.hasOwnProperty('created')) {
      197 |         it('7.1.3 DID Document Metadata - updated is later or equal than created.', async () => {

      at Object.<anonymous> (suites/did-resolution/did-resolution.js:194:48)
```

**Comment by BernhardFuchs** [comment]
@hello2mao Are you aware of this issue?
